//! Dummy Ping Pong Service (L2) built on top of Tensile core (L1)
//! Specification:-
//!    Num Actors:- 2
//!    Common behaviour:- Responds to Ping/Pong Message with a Pong/Ping Message
//!    Special Behaviour:- Actor 1 sends Ping Message at the start
//!
//! Can we prove that Actor 1 will never recieve Ping, and Actor 2 will never recieve Pong?
//! Can we write the specification formally and generate the actor code and
//! prove properties of the system generated by the spec?

use reactor_jobm::JobController;
use reactor_jobm::placement::{LibInfo, LogicalOp, ManualPlacementManager, PhysicalOp};
use std::collections::HashMap;
use std::time::Duration;
use serde_json::Value;

#[tokio::main]
async fn main() {
    let ops = vec![
        LogicalOp {
            name: "pingpong".to_string(),
            lib_name: "ping_pong_actor".to_string(),
        },
    ];
    let pm = ManualPlacementManager {
        map: HashMap::from([
            (
                "pingpong".to_string(),
                vec![PhysicalOp {
                    nodename: "node1".to_string(),
                    actor_name: "pinger".to_string(),
                    payload: HashMap::from([("other".to_string(), Value::String("pinger".to_string()))])
                }],
            ),
            (
                "pingpong".to_string(),
                vec![PhysicalOp {
                    nodename: "node1".to_string(),
                    actor_name: "ponger".to_string(),
                    payload: HashMap::from([("other".to_string(), Value::String("pinger".to_string()))])
                }],
            ),
        ]),
    };
    let mut jc = JobController::new(pm);
    jc.register_node("node1", "127.0.0.1", 3000);
    let lib_info = LibInfo {
        name: "ping_pong_actor".to_string(),
        compile_info: HashMap::new(),
    };
    jc.register_lib(&lib_info, "node1").await;

    jc.start_job(ops).await;
    tokio::time::sleep(Duration::from_secs(10)).await;
    jc.stop_job().await;

}
