//! Dummy Ping Pong Service (L2) built on top of Tensile core (L1)
//! Specification:-
//!    Num Actors:- 2
//!    Common behaviour:- Responds to Ping/Pong Message with a Pong/Ping Message
//!    Special Behaviour:- Actor 1 sends Ping Message at the start
//!
//! Can we prove that Actor 1 will never recieve Ping, and Actor 2 will never recieve Pong?
//! Can we write the specification formally and generate the actor code and
//! prove properties of the system generated by the spec?

use clap::{Parser, Subcommand, arg};
#[cfg(feature="dynop")]
use reactor_node::code_gen::CodeGenerator;
use reactor_node::node_controller;
use serde_json::Value;
use std::collections::HashMap;
use std::path::PathBuf;
use std::time::Duration;

#[derive(Parser)]
#[command(name = "Reactor", about = "Run a reactor node or a job manager")]
pub struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Run a reactor node
    Node {
        #[arg(short, long)]
        port: u16,
        #[cfg(not(feature = "dynop"))]
        dir: PathBuf,
    },
}

#[tokio::main]
async fn main() {
    let cli = Cli::parse();
    #[cfg(feature="dynop")]
    let cg = PingPongCodeGen {};
    match cli.command {
        #[cfg(feature = "dynop")]
        Commands::Node { port } => node_controller(cg, port).await,
        #[cfg(not(feature = "dynop"))]
        Commands::Node { port, dir } => node_controller(port, dir).await,
    }
}
