//! Dummy Ping Pong Service (L2) built on top of Tensile core (L1)
//! Specification:-
//!    Num Actors:- 2
//!    Common behaviour:- Responds to Ping/Pong Message with a Pong/Ping Message
//!    Special Behaviour:- Actor 1 sends Ping Message at the start
//!
//! Can we prove that Actor 1 will never recieve Ping, and Actor 2 will never recieve Pong?
//! Can we write the specification formally and generate the actor code and
//! prove properties of the system generated by the spec?

use std::{sync::Arc, time::Duration};

use bincode::{Decode, Encode};
use tensile_core::{
    actor::{
        ActorAddr, ChannelAction, DecodeErr, Generator, Msg, RState, SState, State,
        common::sender_task,
    },
    node::{ControlInst, ControlReq, node_controller},
};
use tokio::sync::{
    Mutex,
    mpsc::{self, channel, unbounded_channel},
};
use tokio_util::bytes::{Bytes, BytesMut};

// //////////////////////////////////////////////////////////////////////////////
//                                    MSG
// //////////////////////////////////////////////////////////////////////////////
#[derive(Encode, Decode, Debug)]
pub enum PingPongMsg {
    Ping,
    Pong,
}

impl Msg for PingPongMsg {}

// //////////////////////////////////////////////////////////////////////////////
//                                RECEIVER STATE
// //////////////////////////////////////////////////////////////////////////////
#[derive(Default)]
struct ChannelState {}
impl RState for ChannelState {}

// //////////////////////////////////////////////////////////////////////////////
//                                PROCESSOR STATE
// //////////////////////////////////////////////////////////////////////////////
#[derive(Default)]
pub struct PingPongState {}
impl State for PingPongState {}

// //////////////////////////////////////////////////////////////////////////////
//                                  SENDER STATE
// //////////////////////////////////////////////////////////////////////////////
#[derive(Default)]
struct RouterState {
    _my_addr: ActorAddr,
    other_addr: ActorAddr,
}
impl SState for RouterState {}

// //////////////////////////////////////////////////////////////////////////////
//                                  CALLBACKS
// //////////////////////////////////////////////////////////////////////////////
fn after_recv(_msg: &PingPongMsg, _channel_state: &Arc<Mutex<ChannelState>>) -> ChannelAction {
    println!("Rcvd {_msg:?}");
    ChannelAction::PASS
}

fn processor(msg: PingPongMsg, _state: &mut PingPongState) -> PingPongMsg {
    std::thread::sleep(Duration::from_secs(1));
    match msg {
        PingPongMsg::Ping => PingPongMsg::Pong,
        PingPongMsg::Pong => PingPongMsg::Ping,
    }
}

fn before_send(_msg: &PingPongMsg, state: &mut RouterState) -> ActorAddr {
    println!("Sent {_msg:?}");
    state.other_addr
}

// //////////////////////////////////////////////////////////////////////////////
//                                  CODEC
// //////////////////////////////////////////////////////////////////////////////

#[derive(Clone)]
pub struct PingPongCodec {
    config: bincode::config::Configuration,
    length_codec: tokio_util::codec::LengthDelimitedCodec,
}
impl PingPongCodec {
    pub fn new() -> Self {
        PingPongCodec {
            config: bincode::config::standard(),
            length_codec: tokio_util::codec::LengthDelimitedCodec::builder()
                .length_field_length(4)
                .max_frame_length(u32::MAX as usize)
                .new_codec(),
        }
    }
}
impl tokio_util::codec::Decoder for PingPongCodec {
    type Item = PingPongMsg;
    type Error = DecodeErr;

    fn decode(&mut self, src: &mut BytesMut) -> Result<Option<Self::Item>, Self::Error> {
        let frame = match self.length_codec.decode(src).map_err(|_| DecodeErr)? {
            Some(frame) => frame,
            None => return Ok(None),
        };
        let (message, _) =
            bincode::decode_from_slice(&frame, self.config).map_err(|_| DecodeErr)?;

        Ok(Some(message))
    }
}
impl tokio_util::codec::Encoder<PingPongMsg> for PingPongCodec {
    type Error = std::io::Error;

    fn encode(&mut self, item: PingPongMsg, dst: &mut BytesMut) -> Result<(), Self::Error> {
        let encoded_data = bincode::encode_to_vec(&item, self.config).map_err(|_| {
            std::io::Error::new(std::io::ErrorKind::InvalidData, "Failed to encode data")
        })?;
        self.length_codec
            .encode(Bytes::from(encoded_data), dst)
            .map_err(|_| {
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    "Couldn't encode length-delimited data",
                )
            })?;

        Ok(())
    }
}

// //////////////////////////////////////////////////////////////////////////////
//                                ACTORS
// //////////////////////////////////////////////////////////////////////////////

fn gen_ping(_i: u64, _s: &mut ()) -> PingPongMsg {
    PingPongMsg::Ping
}

pub async fn actor(
    controller_rx: mpsc::UnboundedReceiver<ControlInst>,
    controller_tx: mpsc::Sender<ControlReq>,
    my_addr: ActorAddr,
    other_addr: ActorAddr,
) {
    let mut generators = Vec::new();
    if my_addr == "pinger" {
        generators.push(Generator {
            s: (),
            callback: gen_ping,
            start: Duration::from_millis(1),
            interval: Duration::from_secs(1),
            max: Some(1),
        });
    }
    tensile_core::actor::actor(
        my_addr,
        generators,
        ChannelState::default(),
        after_recv,
        processor,
        RouterState {
            _my_addr: my_addr,
            other_addr,
        },
        before_send,
        PingPongCodec::new(),
        controller_rx,
        controller_tx,
        sender_task,
    )
    .await;
}

#[tokio::main]
async fn main() {
    env_logger::init();

    let node_addr = "nodex.cse.iitd.ac.in";
    let (actor1_port, actor2_port) = (50000, 50001);

    // Start node controller
    let (node_tx, node_rx) = channel::<ControlReq>(32);
    let handle1 = tokio::spawn(node_controller(node_rx, node_addr));

    // Spawn Pinger
    let (actor_control_tx, actor_control_rx) = unbounded_channel();
    let handle2 = tokio::spawn(actor(actor_control_rx, node_tx.clone(), "pinger", "ponger"));

    // Notify Node Controller
    node_tx
        .send(ControlReq::ActorAdded {
            addr: "pinger",
            actor_control_tx,
            node_addr,
            recv_port: actor1_port,
        })
        .await
        .unwrap();

    // Spawn Ponger
    let (actor_control_tx, actor_control_rx) = unbounded_channel();
    let handle3 = tokio::spawn(actor(actor_control_rx, node_tx.clone(), "ponger", "pinger"));

    // Notify Node Controller
    node_tx
        .send(ControlReq::ActorAdded {
            addr: "ponger",
            actor_control_tx,
            node_addr,
            recv_port: actor2_port,
        })
        .await
        .unwrap();

    handle1.await.unwrap();
    handle2.await.unwrap();
    handle3.await.unwrap();
}
