//! Dummy Ping Pong Service (L2) built on top of Tensile core (L1)
//! Specification:-
//!    Num Actors:- 2
//!    Common behaviour:- Responds to Ping/Pong Message with a Pong/Ping Message
//!    Special Behaviour:- Actor 1 sends Ping Message at the start
//!
//! Can we prove that Actor 1 will never recieve Ping, and Actor 2 will never recieve Pong?
//! Can we write the specification formally and generate the actor code and
//! prove properties of the system generated by the spec?

use clap::{Parser, command};
use reactor_jobm::JobController;
use reactor_jobm::placement::{LogicalOp, ManualPlacementManager, NodeInfo, PhysicalOp};
use serde::Deserialize;
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use tokio::signal;

#[derive(Debug, Deserialize, PartialEq, Eq)]
pub struct JobManifest {
    pub nodes: Vec<NodeInfo>,
    pub ops: Vec<LogicalOp>,
    pub placement: HashMap<String, Vec<PhysicalOp>>,
}

#[derive(Parser)]
#[command(name = "Job Controller", about = "Run reactor Job controller")]
pub struct Cli {
    pub job_manifest: PathBuf,
}

#[tokio::main]
async fn main() {
    let cli = Cli::parse();
    let contents = fs::read_to_string(cli.job_manifest).expect("File doesn't exist");
    let job_manifest: JobManifest = toml::from_str(&contents).expect("Toml Parse error");

    let ops = job_manifest.ops;

    let mut actual_placements: HashMap<String, Vec<PhysicalOp>> = HashMap::new();
    for (op, value) in job_manifest.placement.into_iter() {
        let mut temp_vec: Vec<PhysicalOp> = Vec::new();
        for phys_op in value {
            if let Some(replicas) = phys_op.replicas {
                for i in 1..=replicas {
                    temp_vec.push(PhysicalOp {
                        nodename: phys_op.nodename.clone(),
                        actor_name: format!("{}{}", phys_op.actor_name, i),
                        payload: phys_op.payload.clone(),
                        replicas: None,
                    });
                }
            } else {
                temp_vec.push(phys_op);
            }
        }
        actual_placements.insert(op.clone(), temp_vec);
    }

    let pm = ManualPlacementManager {
        map: actual_placements,
    };
    let mut jc = JobController::new(pm);

    for node in job_manifest.nodes {
        jc.register_node(&node.name, node.hostname.leak(), node.port);
    }

    jc.start_job(ops).await;
    let _ = signal::ctrl_c().await;
    jc.stop_job().await;
}

#[cfg(test)]
mod tests {
    use super::*;
    use reactor_jobm::placement::PhysicalOp;
    use serde_json::json;
    use std::collections::HashMap;

    #[test]
    fn test_manual_placement_manager_parse() {
        let toml_data = r#"
[[ops]]
name = "pinger"
lib_name = "ping_pong_actor"

[[ops]]
name = "ponger"
lib_name = "ping_pong_actor"

[[nodes]]
name = "node1"
hostname = "0.0.0.0"
port = 3000

[placement]
  [[placement.pinger]]
  nodename = "node1"
  actor_name = "pinger"
  other = "ponger"

  [[placement.ponger]]
  nodename = "node1"
  actor_name = "ponger"
  replicas = 3
  connection = { hashed = ["addr1", "addr2"] }
  op_args = { height = 1080, width = 1920, source = { type = "rtsp", url = "rtsp://example.com/stream" } }
"#;

        let parsed: JobManifest = toml::from_str(toml_data).expect("Failed to parse");

        let expected = JobManifest {
            ops: vec![
                LogicalOp {
                    name: "pinger".into(),
                    lib_name: "ping_pong_actor".into(),
                },
                LogicalOp {
                    name: "ponger".into(),
                    lib_name: "ping_pong_actor".into(),
                },
            ],
            placement: HashMap::from([
                (
                    "pinger".into(),
                    vec![PhysicalOp {
                        nodename: "node1".into(),
                        actor_name: "pinger".into(),
                        payload: HashMap::from([("other".to_string(), json!("ponger"))]),
                        replicas: None,
                    }],
                ),
                (
                    "ponger".into(),
                    vec![PhysicalOp {
                        nodename: "node1".into(),
                        actor_name: "ponger".into(),
                        payload: HashMap::from([
                            (
                                "connection".to_string(),
                                json!({"hashed": ["addr1", "addr2"]}),
                            ),
                            (
                                "op_args".to_string(),
                                json!( {
                                    "height": 1080,
                                    "width":  1920,
                                    "source": { "type": "rtsp", "url": "rtsp://example.com/stream" }
                                } ),
                            ),
                        ]),
                        replicas: Some(3),
                    }],
                ),
            ]),
            nodes: vec![NodeInfo {
                name: "node1".to_string(),
                hostname: "0.0.0.0".to_string(),
                port: 3000,
            }],
        };

        assert_eq!(parsed, expected);
    }
}
