//! Dummy Ping Pong Service (L2) built on top of Tensile core (L1)
//! Specification:-
//!    Num Actors:- 2
//!    Common behaviour:- Responds to Ping/Pong Message with a Pong/Ping Message
//!    Special Behaviour:- Actor 1 sends Ping Message at the start
//!
//! Can we prove that Actor 1 will never recieve Ping, and Actor 2 will never recieve Pong?
//! Can we write the specification formally and generate the actor code and
//! prove properties of the system generated by the spec?

use askama::Template;
use clap::{Parser, Subcommand, arg};
use reactor_jobm::JobController;
use reactor_jobm::placement::{LogicalOp, ManualPlacementManager, PhysicalOp};
use reactor_node::code_gen::CodeGenerator;
use reactor_node::node_controller;
use serde_json::Value;
use std::collections::HashMap;
use std::time::Duration;

const CARGO_TOML: &str = r#"
[package]
name = "ping_pong_actor"
version = "0.1.0"
rust-version = "1.86"
edition = "2024"

[lib]
name = "ping_pong"
crate-type = ["cdylib"]


[dependencies]
ping_pong = { path = "/home/satyam/dev/reactor/examples/ping_pong" }
tokio = { version = "1", features = ["full"] }
reactor-actor = { path = "/home/satyam/dev/reactor/actor" }
lazy_static = "1.5.0"
env_logger = "0.11"
"#;

#[derive(Template)]
#[template(
    source = "
use ping_pong::actor;
use tokio::sync::{Mutex, mpsc};
use reactor_actor::ControlReq;
use reactor_actor::ControlInst;
pub use reactor_actor::setup_shared_logger_ref;
use lazy_static;

lazy_static::lazy_static! {
    static ref RUNTIME: tokio::runtime::Runtime = tokio::runtime::Runtime::new().unwrap();
}

#[unsafe(no_mangle)]
pub extern \"C\" fn actor_callback(
    inst_recv: mpsc::UnboundedReceiver<ControlInst>,
    req_send: mpsc::Sender<ControlReq>,
    actor_name: &'static str,
) {
    RUNTIME.spawn(actor(inst_recv, req_send, actor_name, \"{{other}}\"));
}
",
    ext = "txt"
)]
struct LibTemplate<'a> {
    other: &'a str,
}

struct PingPongCodeGen;

impl CodeGenerator for PingPongCodeGen {
    fn generate(
        &self,
        op_name: &str,
        args: std::collections::HashMap<String, Value>,
    ) -> (String, String) {
        let template = LibTemplate {
            other: args.get("other").unwrap().as_str().unwrap(),
        };
        (template.render().expect(""), CARGO_TOML.to_string())
    }
}

#[derive(Parser)]
#[command(name = "Reactor", about = "Run a reactor node or a job manager")]
pub struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Run a reactor node
    Node {
        #[arg(short, long)]
        port: u16,
    },
    /// Run the job manager
    JobManager,
}

#[tokio::main]
async fn main() {
    let cli = Cli::parse();
    let ops = vec![
        LogicalOp {
            name: "pinger".to_string(),
            compile_info: HashMap::from([("other".to_string(), Value::from("ponger"))]),
        },
        LogicalOp {
            name: "ponger".to_string(),
            compile_info: HashMap::from([("other".to_string(), Value::from("pinger"))]),
        },
    ];
    let pm = ManualPlacementManager {
        map: HashMap::from([
            (
                "pinger".to_string(),
                vec![PhysicalOp {
                    logical: (&ops[0]).clone(),
                    nodename: "node1".to_string(),
                    actor_name: "pinger".to_string(),
                    idx: 0,
                    peers: 1,
                }],
            ),
            (
                "ponger".to_string(),
                vec![PhysicalOp {
                    logical: (&ops[1]).clone(),
                    nodename: "node1".to_string(),
                    actor_name: "ponger".to_string(),
                    idx: 0,
                    peers: 1,
                }],
            ),
        ]),
    };
    let cg = PingPongCodeGen {};
    match cli.command {
        Commands::Node { port } => node_controller(cg, port).await,
        Commands::JobManager => {
            let mut gc = JobController::new(pm);
            gc.register_node("node1", "0.0.0.0");
            gc.register_op(&ops[0], "node1").await;
            gc.register_op(&ops[1], "node1").await;
            gc.start_job(ops).await;
            tokio::time::sleep(Duration::from_secs(5)).await;
            gc.stop_job().await;
        }
    }
}
