//! Dummy Ping Pong Service (L2) built on top of Tensile core (L1)
//! Specification:-
//!    Num Actors:- 2
//!    Common behaviour:- Responds to Ping/Pong Message with a Pong/Ping Message
//!    Special Behaviour:- Actor 1 sends Ping Message at the start
//!
//! Can we prove that Actor 1 will never recieve Ping, and Actor 2 will never recieve Pong?
//! Can we write the specification formally and generate the actor code and
//! prove properties of the system generated by the spec?

use askama::Template;
use clap::{Parser, Subcommand, arg};
use reactor_jobm::JobController;
use reactor_jobm::placement::{LibInfo, LogicalOp, ManualPlacementManager, PhysicalOp};
#[cfg(feature="dynop")]
use reactor_node::code_gen::CodeGenerator;
use reactor_node::node_controller;
use serde_json::Value;
use std::collections::HashMap;
use std::path::PathBuf;
use std::time::Duration;

extern crate pyroscope;

use pyroscope::{PyroscopeAgent, Result};
use pyroscope_pprofrs::{pprof_backend, PprofConfig};

const CARGO_TOML: &str = r#"
[package]
name = "ping_pong_actor2"
version = "0.1.0"
rust-version = "1.86"
edition = "2024"

[lib]
name = "ping_pong"
crate-type = ["cdylib"]


[dependencies]
tokio = { version = "1", features = ["full"] }
reactor-actor = { path = "/home/satyam/dev/reactor/actor" }
ping_pong = { path = "/home/satyam/dev/reactor/examples/ping_pong" }
lazy_static = "1.5.0"
env_logger = "0.11"
"#;

#[derive(Template)]
#[template(
    source = "
use lazy_static;
use ping_pong::actor;
pub use reactor_actor::setup_shared_logger_ref;
use reactor_actor::ControlInst;
use reactor_actor::ControlReq;
use tokio::sync::{mpsc, Mutex};

lazy_static::lazy_static! {
    static ref RUNTIME: tokio::runtime::Runtime = tokio::runtime::Runtime::new().unwrap();
}

#[unsafe(no_mangle)]
pub extern \"C\" fn pinger(
    inst_recv: mpsc::UnboundedReceiver<ControlInst>,
    req_send: mpsc::Sender<ControlReq>,
    actor_name: &'static str,
) {
    RUNTIME.spawn(actor(inst_recv, req_send, actor_name, \"ponger\"));
}

#[unsafe(no_mangle)]
pub extern \"C\" fn ponger(
    inst_recv: mpsc::UnboundedReceiver<ControlInst>,
    req_send: mpsc::Sender<ControlReq>,
    actor_name: &'static str,
) {
    RUNTIME.spawn(actor(inst_recv, req_send, actor_name, \"pinger\"));
}
", ext = "txt"
)]
struct LibTemplate {}

#[cfg(feature="dynop")]
struct PingPongCodeGen;

#[cfg(feature="dynop")]
impl CodeGenerator for PingPongCodeGen {
    fn generate(&self, args: std::collections::HashMap<String, Value>) -> (String, String) {
        let template = LibTemplate {};
        (template.render().expect(""), CARGO_TOML.to_string())
    }
}

#[derive(Parser)]
#[command(name = "Reactor", about = "Run a reactor node or a job manager")]
pub struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Run a reactor node
    Node {
        #[arg(short, long)]
        port: u16,
        #[cfg(not(feature = "dynop"))]
        dir: PathBuf,
    },
    /// Run the job manager
    JobManager,
}

#[tokio::main]
async fn main() {
    let cli = Cli::parse();
    let ops = vec![
        LogicalOp {
            name: "pinger".to_string(),
        },
        LogicalOp {
            name: "ponger".to_string(),
        },
    ];
    let pm = ManualPlacementManager {
        map: HashMap::from([
            (
                "pinger".to_string(),
                vec![PhysicalOp {
                    logical: (ops[0]).clone(),
                    nodename: "node1".to_string(),
                    actor_name: "pinger".to_string(),
                    idx: 0,
                    peers: 1,
                    lib_name: "ping_pong_actor".to_string(),
                }],
            ),
            (
                "ponger".to_string(),
                vec![PhysicalOp {
                    logical: (ops[1]).clone(),
                    nodename: "node2".to_string(),
                    actor_name: "ponger".to_string(),
                    idx: 0,
                    peers: 1,
                    lib_name: "ping_pong_actor".to_string(),
                }],
            ),
        ]),
    };
    let lib_info = LibInfo {
        name: "ping_pong_actor".to_string(),
        compile_info: HashMap::new(),
    };
    #[cfg(feature="dynop")]
    let cg = PingPongCodeGen {};
    match cli.command {
        #[cfg(feature = "dynop")]
        Commands::Node { port } => node_controller(cg, port).await,
        #[cfg(not(feature = "dynop"))]
        Commands::Node { port, dir } => node_controller(port, dir).await,
        Commands::JobManager => {
            let mut gc = JobController::new(pm);
            gc.register_node("node1", "10.227.52.149");
            gc.register_node("node2", "10.237.20.60"); //node1.cse.iitd.ac.in
            
            #[cfg(feature = "dynop")]
            {
                gc.register_lib(&lib_info, "node1").await;
            }

            let agent = PyroscopeAgent::builder("http://localhost:4040", "example.async")
                .backend(pprof_backend(PprofConfig::new().sample_rate(100)))
                .tags([("TagA", "ValueA"), ("TagB", "ValueB")].to_vec())
                .build()?;

            // Show start time
            let start = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs();
            println!("Start Time: {}", start);
            
            // Start Agent
            let agent_running = agent.start()?;

            
            gc.start_job(ops).await;
            tokio::time::sleep(Duration::from_secs(10)).await;
            gc.stop_job().await;

            // Stop Agent
            let agent_ready = agent_running.stop()?;

            // Shutdown the Agent
            agent_ready.shutdown();

            // Show program exit time
            let exit = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs();
            println!("Exit Time: {}", exit);


        }
    }
}
