direction: right

vars: {
  d2-legend: {
    b: UserProvided {
      shape: rectangle
      style.fill: "#f4a261"
    }
  }
}

classes: {
  state: {
      shape: page
      style.fill: "#f4a261"
  }
  in_edge: {
    style: {
      stroke: "green"
    }
  }
  out_edge: {
    style: {
      stroke: "red"
    }
  }
  rw_edge: {
    style: {
      stroke: "purple"
      stroke-dash: 3
    }
  }
}

actor: "Actor"

# Parents
parent1: "Parent Actor1" {
  shape: "diamond"
}
parent2: "Parent Actor2" {
  shape: "diamond"
}

# Recv to Processor
actor.recv: "Receiver"
actor.gen: "Generators"
actor.gen.style.fill: "#f4a261"

actor.proc_q: "Process Q"
actor.proc_q.shape: queue

actor.recv.state: "Locked RState"
actor.recv.state.class: state
actor.recv.tasks
actor.recv.tasks.sub1: "Recv Sub Task1"
actor.recv.tasks.sub2: "Recv Sub Task2"

parent1 -> actor.recv.tasks.sub1 {
  class: in_edge
}
parent2 ->actor.recv.tasks.sub2{
  class: in_edge
}

actor.recv.tasks.sub1 <-> actor.recv.state {
  class: rw_edge
}
actor.recv.tasks.sub2 <-> actor.recv.state {
  class: rw_edge
}

actor.recv.tasks.sub1 -> actor.proc_q{
  class: in_edge
}
actor.recv.tasks.sub2 -> actor.proc_q{
  class: in_edge
}
actor.gen -> actor.proc_q{
  class: in_edge
}

# Processor to Send
actor.proc: "Processor"
actor.proc.state: "State"
actor.proc.state.class: state
actor.proc.fn: "f(I) -> O"
actor.proc.fn.shape: circle
actor.proc_q -> actor.proc.fn {
  class: in_edge
}
actor.proc.fn -> actor.send_q {
  class: out_edge
}
actor.proc.fn <-> actor.proc.state {
  class: rw_edge 
}
actor.proc.fn.style.fill: "#f4a261"

actor.send_q: "Send Q"
actor.send_q.shape: queue

# Send to Actor
actor.sender: "Sender"
actor.sender.state: "Sender State"
actor.sender.state.class: state
actor.sender.router: "Router"
actor.sender.router.style.fill: "#f4a261"
actor.send_q -> actor.sender.router {
  class: out_edge
}
actor.sender.router <-> actor.sender.state{
  class: rw_edge
}

actor.sender.send_buff1: "SendBuff1"
actor.sender.send_buff2: "SendBuff2"
actor.sender.send_buff1.shape: queue
actor.sender.send_buff2.shape: queue
actor.sender.router -> actor.sender.send_buff1 {
  class: out_edge
}
actor.sender.router -> actor.sender.send_buff2{
  class: out_edge
}
actor.sender.sub1: "Sub Sender1"
actor.sender.sub2: "Sub Sender2"
actor.sender.send_buff1 -> actor.sender.sub1{
  class: out_edge
}
actor.sender.send_buff2 -> actor.sender.sub2{
  class: out_edge
}

actor.sender.sub1 -> child1{
  class: out_edge
}
actor.sender.sub2 -> child2{
  class: out_edge
}

# Parents
child1: "Child Actor1" {
  shape: "diamond"
}
child2: "Child Actor2" {
  shape: "diamond"
}
