[package]
name = "ping_pong"
version = "0.1.0"
edition = "2024"

[lib]
ping_pong = "lib.rs"
crate-type = ["cdylib"]


[dependencies]
serde_json = "1.0"
bincode = { version = "2.0.0", features = ["serde"] }
env_logger = "0.11.8"
tokio = { version = "1", features = ["full", "tracing"] }
tokio-util = { version = "0.7", features = ["full"] }
reactor-actor = { path = "../../actor" }
reactor-node = { path = "../../node" }
reactor-jobm = { path = "../../job_manager" }
clap = { version = "4", features = ["derive"] }
askama = { version = "0.14.0" }
lazy_static = "1.5.0"


[features]
default = []
dynop = ["reactor-node/dynop", "reactor-jobm/dynop"]
swagger = ["reactor-node/swagger"]
