[package]
name = "ping_pong_actor"
version = "0.1.0"
rust-version = "1.86"
edition = "2024"

[lib]
name = "ping_pong_actor"
crate-type = ["cdylib", "rlib"]


[dependencies]
tokio = { version = "1", features = ["full"] }
reactor-actor = { path = "../../actor" }
lazy_static = "1.5.0"
env_logger = "0.11"
bincode = "2.0.1"
tokio-util = "0.7.15"
